name: hlint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: apt-get install --yes hlint
    - name: checkout repo
      uses: actions/checkout@v3
    - name: run hlint
      run: hlint .
